export function getUi() {
  return {
    place: document.getElementById("place"),
    health: document.getElementById("health"),
    keys: document.getElementById("keys"),
    danger: document.getElementById("danger"),
    points: document.getElementById("points"),
    weaponName: document.getElementById("weaponName"),
    ammo: document.getElementById("ammo"),
    day: document.getElementById("day"),
    banner: document.getElementById("banner"),
    startBtn: document.getElementById("startBtn"),
    shopBtn: document.getElementById("shopBtn"),
    shopPanel: document.getElementById("shopPanel"),
    shopClose: document.getElementById("shopClose"),
    shopPoints: document.getElementById("shopPoints"),
    weaponTab: document.getElementById("weaponTab"),
    ammoTab: document.getElementById("ammoTab"),
    weaponList: document.getElementById("weaponList"),
    weaponQuickbar: document.getElementById("weaponQuickbar"),
    joystick: document.getElementById("joystick"),
    joystickKnob: document.getElementById("joystickKnob"),
    fireButton: document.getElementById("fireButton"),
    taskPanel: document.getElementById("taskPanel"),
    taskToggle: document.getElementById("taskToggle"),
    carPointer: document.getElementById("carPointer"),
    carPointerLabel: document.getElementById("carPointerLabel"),
    carDistance: document.getElementById("carDistance"),
    carArrow: document.querySelector(".car-arrow"),
    objectiveToast: document.getElementById("objectiveToast"),
    objectiveTitle: document.getElementById("objectiveTitle"),
    objectiveDetail: document.getElementById("objectiveDetail"),
    threatMeter: document.getElementById("threatMeter"),
    threatLevel: document.getElementById("threatLevel"),
    tasks: Array.from(document.querySelectorAll("#tasks li")),
  };
}
