import { CONFIG, MODE } from "./config.js";

export function createInitialGameState() {
  return {
    mode: MODE.MENU,
    phase: "forest",
    player: { x: 480, y: 320, r: 15, hp: 100, speed: 205, angle: 0, damageCooldown: 0 },
    bullets: [],
    muzzleFlashes: [],
    monsters: [],
    particles: [],
    pickups: [],
    walls: [],
    door: null,
    car: null,
    wreckCar: null,
    parkingLot: null,
    camera: { x: 0, y: 0 },
    scene: null,
    screenShake: 0,
    hidden: false,
    rockHits: {},
    brokenRocks: new Set(),
    removedBushes: new Set(),
    bushHideKey: null,
    bushHideTime: 0,
    points: 0,
    weaponId: "pistol",
    ownedWeapons: ["pistol"],
    ammo: { 1: CONFIG.ammo.initial },
    ammoSpawnTimer: 0,
    medkitSpawnTimer: 0,
    chestSpawnTimer: 0,
    driveChaseTimer: 0,
    vehicleHp: CONFIG.vehicle.hp,
    vehicleDamageCooldown: 0,
    healingTimer: 0,
    healingLevel: 0,
    shopOpen: false,
    shopTab: "weapons",
    foundKeys: 0,
    day: 1,
    driving: false,
    escapeOnFoot: false,
    danger: 1,
    spawnTimer: 0,
    shootCooldown: 0,
    weaponSwitchTimer: 0,
    forestReturn: false,
    won: false,
    searchedTents: new Set(),
    tentSearchCooldown: 0,
  };
}
